version: '3.9'

services:

  app:
    container_name: web
    build: .
    working_dir: /code
    command: uvicorn app:app --host 0.0.0.0 --reload
    environment:
      DEBUG: 1
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: on-failure
